<!--
EMPTY PRODUCT ARRAY
$products[] = array(
	"name" => "",
    "thumb" => "img/thumbs/thumb.jpg",
	"img" => "img/pics/.jpg",
    "description" => "",
	"location" => "",
    "year" => "",
    "aspect" => "11"
);
-->

<?php

function get_list_view_html($product_id, $product) {
    $output = "";
    $output = $output . "<li>";
    $output = $output .  '<a href="' . $product["img"] . '">';
    $output = $output . '<img class="img-circle" src="' . $product["thumb"] . '" alt="' . $product["name"] . '">';
    $output = $output .  "</a>";
    $output = $output .  "</li>"; 
    return $output; 
}


$products[101] = array(
	"name" => "Abstract Yellow Flower",
    "thumb" => "img/thumbs/abstractyellowflowerthumb.jpg",
	"img" => "img/pics/abstractyellowflower.jpg",
    "description" => "A heavily effected shot of a cheap flower I picked up for my wife.",
	"location" => "Columbus, Ohio",
    "year" => "2014",
    "aspect" => "11"
);
$products[102] = array(
	"name" => "Alaska Light",
    "thumb" => "img/thumbs/aklightthumb.jpg",
	"img" => "img/pics/aklight.jpg",
    "description" => "Snow falling around a streetlight in Fairbanks, Alaska",
	"location" => "Fairbanks, Alaska",
    "year" => "2009",
    "aspect" => "11"
);
$products[103] = array(
	"name" => "Dakota Badlands",
    "thumb" => "img/thumbs/badlandsthumb.jpg",
	"img" => "img/pics/badlands.jpg",
    "description" => "North Dakota Badlands in Summer",
	"location" => "Western North Dakota",
    "year" => "2014",
    "aspect" => "21"
);
$products[104] = array(
	"name" => "Chief Mountain",
    "thumb" => "img/thumbs/chiefmtthumb.jpg",
	"img" => "img/pics/chiefmt.jpg",
    "description" => "Sunset near Chief Mountain.",
	"location" => "Cheif Mountain. Glacier National Park, Montana",
    "year" => "2014",
    "aspect" => "21"
);
$products[105] = array(
	"name" => "City Seoul",
    "thumb" => "img/thumbs/citysoulthumb.jpg",
	"img" => "img/pics/citysoul.jpg",
    "description" => "Sunset over Seoul, South Korea",
	"location" => "Seoul, South Korea",
    "year" => "2009",
    "aspect" => "21"
);
$products[106] = array(
	"name" => "Clark Range",
    "thumb" => "img/thumbs/clarkrangethumb.jpg",
	"img" => "img/pics/clarkrange.jpg",
    "description" => "The Clark Range. Yosemite National Park, California",
	"location" => "Yosemite National Park, California",
    "year" => "2009",
    "aspect" => "11"
);
$products[107] = array(
	"name" => "Crystal Lake",
    "thumb" => "img/thumbs/crystalthumb.jpg",
	"img" => "img/pics/crystal.jpg",
    "description" => "Sunrise at Crystal Lake.",
	"location" => "Lewis and Clark National Forest, Montana",
    "year" => "2014",
    "aspect" => "21"
);
$products[108] = array(
	"name" => "Dakota Sky",
    "thumb" => "img/thumbs/dakotathumb.jpg",
	"img" => "img/pics/dakota.jpg",
    "description" => "The rain begins to break away in central North Dakota",
	"location" => "Central North Dakota",
    "year" => "2014",
    "aspect" => "21"
);$products[109] = array(
	"name" => "focus",
    "thumb" => "img/thumbs/focusthumb.jpg",
	"img" => "img/pics/focus.jpg",
    "description" => "A well focused shot of an ant crawling on a flower petal.",
	"location" => "Glacier National Park, Montana",
    "year" => "2014",
    "aspect" => "11"
);$products[110] = array(
	"name" => "Glacier Field",
    "thumb" => "img/thumbs/glacierthumb.jpg",
	"img" => "img/pics/glacier.jpg",
    "description" => "An open field at sunset. Just east of Glacier National Park",
	"location" => "Glacier National Park, Montana",
    "year" => "2014",
    "aspect" => "21"
);$products[111] = array(
	"name" => "Glacier Flower",
    "thumb" => "img/thumbs/glacierflowerthumb.jpg",
	"img" => "img/pics/glacierflower.jpg",
    "description" => "A gorgeous close up of a flower near Lake Mary.",
	"location" => "Glacier National Park, Montana",
    "year" => "2014",
    "aspect" => "11"
);$products[112] = array(
	"name" => "Grand Prismatic Spring",
    "thumb" => "img/thumbs/gpsthumb.jpg",
	"img" => "img/pics/gps.jpg",
    "description" => "The Grand Prismatic Spring",
	"location" => "Yellowstone National Park, Wyoming",
    "year" => "2014",
    "aspect" => "21"
);$products[113] = array(
	"name" => "Hawaii Bird",
    "thumb" => "img/thumbs/hibirdthumb.jpg",
	"img" => "img/pics/hibird.jpg",
    "description" => "A bird flies into my shot in Hawaii.",
	"location" => "Oahu, Hawaii",
    "year" => "2010",
    "aspect" => "11"
);$products[114] = array(
	"name" => "Hawaii Mountain",
    "thumb" => "img/thumbs/himtnthumb.jpg",
	"img" => "img/pics/himtn.jpg",
    "description" => "A breathtaking view of northern Oahu.",
	"location" => "Oahu, Hawaii",
    "year" => "2010",
    "aspect" => "21"
);$products[115] = array(
	"name" => "Room with a view",
    "thumb" => "img/thumbs/hiviewthumb.jpg",
	"img" => "img/pics/hiview.jpg",
    "description" => "The view from my hotel room in Hawaii.",
	"location" => "Oahu, Hawaii",
    "year" => "2010",
    "aspect" => "11"
);$products[116] = array(
	"name" => "Hawaii Sunrise",
    "thumb" => "img/thumbs/hisunrisethumb.jpg",
	"img" => "img/pics/hisunrise.jpg",
    "description" => "The sun rises on Oahu&#39;s north shore",
	"location" => "Oahu, Hawaii",
    "year" => "2010",
    "aspect" => "11"
);$products[117] = array(
	"name" => "HI Water",
    "thumb" => "img/thumbs/hiwaterthumb.jpg",
	"img" => "img/pics/hiwater.jpg",
    "description" => "Water recedes back after a wave hit the rocks on Oahu&#39;s north shore.",
	"location" => "Oahu, Hawaii",
    "year" => "2010",
    "aspect" => "11"
);$products[118] = array(
	"name" => "And they drove off into the sunset...",
    "thumb" => "img/thumbs/intothesunsetthumb.jpg",
	"img" => "img/pics/intothesunset.jpg",
    "description" => "Sun sets on the first night of our Honeymoon Road Trip.",
	"location" => "Somewhere in the Midwest",
    "year" => "2014",
    "aspect" => "21"
);$products[119] = array(
	"name" => "Jenny's Falls",
    "thumb" => "img/thumbs/jennyfallsthumb.jpg",
	"img" => "img/pics/jennyfalls.jpg",
    "description" => "A waterfall/tree dam in the river feeding Jenny Lake.",
	"location" => "Grand Teton National Park, Wyoming",
    "year" => "2014",
    "aspect" => "21"
);$products[120] = array(
	"name" => "Jenny's Flower",
    "thumb" => "img/thumbs/jennyflowerthumb.jpg",
	"img" => "img/pics/jennyflower.jpg",
    "description" => "A beautiful flower on the Jenny Lake Trail",
	"location" => "Grand Teton National Park, Wyoming",
    "year" => "2014",
    "aspect" => "11"
);$products[121] = array(
	"name" => "Leaf",
    "thumb" => "img/thumbs/leafthumb.jpg",
	"img" => "img/pics/leaf.jpg",
    "description" => "Water resting on a leaf I found on a bench.",
	"location" => "Columbus, Ohio",
    "year" => "2014",
    "aspect" => "21"
);$products[122] = array(
	"name" => "The Road Less Traveled",
    "thumb" => "img/thumbs/lewisnclarkthumb.jpg",
	"img" => "img/pics/lewisnclark.jpg",
    "description" => "The road leading to Crystal Lake",
	"location" => "Lewis and Clark National Forest, Montana",
    "year" => "2014",
    "aspect" => "21"
);$products[123] = array(
	"name" => "Logans Pass, East",
    "thumb" => "img/thumbs/loganthumb.jpg",
	"img" => "img/pics/logan.jpg",
    "description" => "Just east of Logan's Pass.",
	"location" => "Glacier National Park, Montana",
    "year" => "2014",
    "aspect" => "21"
);$products[124] = array(
	"name" => "Logan's Falls",
    "thumb" => "img/thumbs/loganfallsthumb.jpg",
	"img" => "img/pics/loganfalls.jpg",
    "description" => "Waterfall west of Logan's Pass.",
	"location" => "Glacier National Park, Montana",
    "year" => "2014",
    "aspect" => "12"
);$products[125] = array(
	"name" => "Montana Flatlands",
    "thumb" => "img/thumbs/montanaflatsthumb.jpg",
	"img" => "img/pics/montanaflats.jpg",
    "description" => "Dry flatlands in eastern Montana",
	"location" => "Eastern Montana",
    "year" => "2014",
    "aspect" => "21"
);$products[126] = array(
	"name" => "Morning Creek",
    "thumb" => "img/thumbs/morningcreekthumb.jpg",
	"img" => "img/pics/morningcreek.jpg",
    "description" => "A creek after sunrise as we hit the road again.",
	"location" => "Lewis and Clark National Forest, Montana",
    "year" => "2014",
    "aspect" => "21"
);$products[127] = array(
	"name" => "Mosquito Hell",
    "thumb" => "img/thumbs/mosquitohellthumb.jpg",
	"img" => "img/pics/mosquitohell.jpg",
    "description" => "A stunning area with the meanest mosquitos I have ever encountered in my entire life.",
	"location" => "Western Montana",
    "year" => "2014",
    "aspect" => "21"
);$products[128] = array(
	"name" => "Korean Garden",
    "thumb" => "img/thumbs/palacethumb.jpg",
	"img" => "img/pics/palace.jpg",
    "description" => "A garden in a Palace in South Korea",
	"location" => "Seoul, South Korea",
    "year" => "2009",
    "aspect" => "11"
);$products[129] = array(
	"name" => "Winter Palms",
    "thumb" => "img/thumbs/palmthumb.jpg",
	"img" => "img/pics/palm.jpg",
    "description" => "Palm trees in February.",
	"location" => "Oahu, Hawaii",
    "year" => "2010",
    "aspect" => "11"
);$products[130] = array(
	"name" => "Palace Pond",
    "thumb" => "img/thumbs/pondthumb.jpg",
	"img" => "img/pics/pond.jpg",
    "description" => "A structure by a pond in a South Korean Palace.",
	"location" => "Seoul, South Korea",
    "year" => "2009",
    "aspect" => "11"
);$products[131] = array(
	"name" => "Palace Pond 2",
    "thumb" => "img/thumbs/pond2thumb.jpg",
	"img" => "img/pics/pond2.jpg",
    "description" => "A pond in a South Korean Palace",
	"location" => "Seoul, South Korea",
    "year" => "2009",
    "aspect" => "21"
);$products[132] = array(
	"name" => "Snake River",
    "thumb" => "img/thumbs/snakeriverthumb.jpg",
	"img" => "img/pics/snakeriver.jpg",
    "description" => "The Snake River",
	"location" => "Wyoming",
    "year" => "2014",
    "aspect" => "21"
);$products[133] = array(
	"name" => "Spaced",
    "thumb" => "img/thumbs/spacethumb.jpg",
	"img" => "img/pics/space.jpg",
    "description" => "The Space Needle, shot through a sunroof on a limo we rented.",
	"location" => "Seattle, Washington",
    "year" => "2009",
    "aspect" => "11"
);$products[134] = array(
	"name" => "Trunked",
    "thumb" => "img/thumbs/trunkedthumb.jpg",
	"img" => "img/pics/trunked.jpg",
    "description" => "Driftwood stumps in Yellowstone Lake",
	"location" => "Yellowstone National Park, Wyoming",
    "year" => "2014",
    "aspect" => "21"
);$products[135] = array(
	"name" => "Turtle",
    "thumb" => "img/thumbs/turtlethumb.jpg",
	"img" => "img/pics/turtle.jpg",
    "description" => "A very active turtle in an aquarium.",
	"location" => "Columbus, Ohio",
    "year" => "2014",
    "aspect" => "11"
);$products[136] = array(
	"name" => "Union Pass",
    "thumb" => "img/thumbs/unionpassthumb.jpg",
	"img" => "img/pics/unionpass.jpg",
    "description" => "Far off the beaten path.",
	"location" => "Grand Teton National Forest, Wyoming",
    "year" => "2014",
    "aspect" => "21"
);$products[137] = array(
	"name" => "Hawaii Wave",
    "thumb" => "img/thumbs/wavethumb.jpg",
	"img" => "img/pics/wave.jpg",
    "description" => "A wave breaks on Oahu's north shore.",
	"location" => "Oahu, Hawaii",
    "year" => "2009",
    "aspect" => "21"
);$products[138] = array(
	"name" => "West Glacier",
    "thumb" => "img/thumbs/westglacierthumb.jpg",
	"img" => "img/pics/westglacier.jpg",
    "description" => "Near the western exit of Glacier National Park.",
	"location" => "Glacier National Park, Montana",
    "year" => "2014",
    "aspect" => "12"
);$products[139] = array(
	"name" => "Yosemite Valley",
    "thumb" => "img/thumbs/yosemitevalleythumb.jpg",
	"img" => "img/pics/yosemitevalley.jpg",
    "description" => "The river in Yosemite Valley.",
	"location" => "Yosemite National Park, California",
    "year" => "2009",
    "aspect" => "11"
);$products[140] = array(
	"name" => "Yellowstone Falls",
    "thumb" => "img/thumbs/ysfallsthumb.jpg",
	"img" => "img/pics/ysfalls.jpg",
    "description" => "A waterfall in Yellowstone National Park",
	"location" => "Yellowstone National Park, Wyoming",
    "year" => "2014",
    "aspect" => "21"
);$products[141] = array(
	"name" => "Yellowstone Flower",
    "thumb" => "img/thumbs/ysflowerthumb.jpg",
	"img" => "img/pics/ysflower.jpg",
    "description" => "A brilliant yellow flower cluster grows in otherwise inhospitable dirt.",
	"location" => "Yellowstone National Park, Wyoming",
    "year" => "2014",
    "aspect" => "11"
);$products[142] = array(
	"name" => "Yellowstone Lake Flowers",
    "thumb" => "img/thumbs/yslakethumb.jpg",
	"img" => "img/pics/yslake.jpg",
    "description" => "Flowers next to Yellowstone Lake",
	"location" => "Yellowstone National Park, Wyoming",
    "year" => "2014",
    "aspect" => "11"
);